### PR TITLE
adds documentation for enabling CORS on the CiviCRM host server

### PR DESCRIPTION
**Pull request by hesco**
This added documentation reflects what I learned enabling a successful installation and configuration of the RemoteForms CiviCRM extension.  I suspect that the user interface provided by RemoteForms at /civicrm/admin/remoteform may have been intended to configure CORS access to the host server site.  But that failed to work for me.  I was nonetheless able to get my (initial) form (mostly) working using the guidance I sorted out and documented in the pull request.  These instructions assume that your extension works to enable CORS access for most sites, and frames the process described, as a back up in case it does not.  

I hope you find this useful.

### CODE REVIEW

**Comment by hesco** [comment]
Reading this:
https://github.com/progressivetech/net.ourpowerbase.remoteform/issues/22 

suggests that perhaps my approach is unique to drupal 8/9
and that your original code probably works for drupal 7

If you understand this well enough to know if that is true, please let me know and I will massage this new documentation to make it clear that my alternate approach is drupal 8/9 specific.  

In the week I spent futzing with this before getting something that worked, I also tested adding to my composer,json, the drupal/advanced_cors and drupal/cors_ui, but was unable to get either to consistently work to manage my service.yml file and so abandoned them for manually editing the configuration.  

The drupal/advanced_cors looked really nice, even if I could not make it work.  Perhaps creating a dependency (for drupal 8/9 installations) on it might serve to simplify what is required in the RemoteForms extension.  Have not read enough of any of this code to know if that would be helpful.

**Comment by jmcclelland** [comment]
Thanks so much for these documentation changes! Very much appreciated.

And yes, the directions as written work for Drupal 7 - so if you could adjust the pull request to reflect that the Drupal changes you've added only apply to Drupal 8/9 that would be great.

Also, I found the "client/server" distinction sensible when I'm wearing my network admin hat, but I suspect many users won't understand which is the client and which is the server. What if we called them: Drupal Website (`drupal-website.md`), Drupal CiviCRM (`drupal-civicrm`), Wordpress Web site (`wordpress-website`), and Wordpress CiviCRM (`wordpress-civicrm`) to try to make it clearer?

**Comment by hesco** [comment]
https://github.com/progressivetech/net.ourpowerbase.remoteform/pull/43#commits-pushed-99473d6

On Wed, 09 Jun 2021 07:49:30 -0700
Jamie McClelland ***@***.***> wrote:

> Thanks so much for these documentation changes! Very much appreciated.
> 
> And yes, the directions as written work for Drupal 7 - so if you could adjust the pull request to reflect that the Drupal changes you've added only apply to Drupal 8/9 that would be great.
> 
> Also, I found the "client/server" distinction sensible when I'm wearing my network admin hat, but I suspect many users won't understand which is the client and which is the server. What if we called them: Drupal Website (`drupal-website.md`), Drupal CiviCRM (`drupal-civicrm`), Wordpress Web site (`wordpress-website`), and Wordpress CiviCRM (`wordpress-civicrm`) to try to make it clearer?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/progressivetech/net.ourpowerbase.remoteform/pull/43#issuecomment-857761316


-- 
Hugh Esco ***@***.***>

**Comment by jmcclelland** [comment]
Thank you!

**Comment by hesco** [comment]
Thank you!

On Wed, 09 Jun 2021 14:33:36 -0700
Jamie McClelland ***@***.***> wrote:

> Merged #43 into master.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/progressivetech/net.ourpowerbase.remoteform/pull/43#event-4867819552


-- 
Hugh Esco ***@***.***>

**Pull request merged**
